# Generated by Django 4.1.3 on 2023-02-13 09:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('creatingTime', models.DateField(default=datetime.date(2023, 2, 13))),
                ('confirmedTime', models.DateField(null=True)),
                ('state', models.CharField(choices=[('A', 'Processing'), ('B', 'WaitingPayment'), ('C', 'Confirmed'), ('D', 'Rejected')], default='A', max_length=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='./static/logos')),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('S', 'Sellable'), ('D', 'Deleted')], default='S', max_length=1)),
                ('price', models.FloatField()),
                ('category', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, upload_to='./static/prods')),
                ('description', models.CharField(max_length=1000)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppsproj.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('state', models.CharField(choices=[('P', 'Processing'), ('A', 'Accepted'), ('R', 'Rejected')], default='P', max_length=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ppsproj.product')),
                ('shCart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppsproj.shoppingcart')),
            ],
        ),
    ]
